# Generated by Django 5.0.7 on 2024-08-11 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("approved", "Approved"),
                    ("pending", "Pending"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="investment",
            name="investor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="investments",
                to="accounts.userprofile",
            ),
        ),
    ]
