# Generated by Django 5.0.7 on 2024-08-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0003_alter_investment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("aprovada", "Aprovada"),
                    ("pendente", "Pendente"),
                    ("rejeitada", "Rejeitada"),
                ],
                default="pendente",
                max_length=10,
            ),
        ),
    ]
