# Generated by Django 5.0.7 on 2024-08-12 22:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0004_alter_investment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
