# Generated by Django 5.0.7 on 2024-08-12 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enterprise",
            name="cnpj",
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="enterprise",
            name="user_profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enterprise",
                to="accounts.userprofile",
            ),
        ),
    ]
