# Generated by Django 5.0.7 on 2024-08-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Idea",
        ),
    ]
